---
deployment:
  tasks:
    - npm install
    - npm run build
    - export BUILD_PATH=$HOME/public_html/repository/build
    - export DEPLOY_PATH=$HOME/public_html
    - /bin/rm -rf $DEPLOY_PATH/*
    - /bin/cp -R $BUILD_PATH/* $DEPLOY_PATH
