export const facultyData = {
  teaching: [
    {
      id: 'faculty-1',
      name: 'Dr. Bhaskara Raju Vatchavai',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Professor & Principal',
      profile: '/public/uploads/pdfs/faculty/Dr.V.BhaskaraRaju.pdf',
    },
    {
      id: 'faculty-2',
      name: 'Dr. P. Narayana Raju',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Professor & HoD',
      profile: '/public/uploads/pdfs/faculty/Dr. P. Narayana Raju.pdf',
    },
    {
      id: 'faculty-3',
      name: 'Dr. Y. B. Manjulatha',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Professor & HoD',
      profile: '/public/uploads/pdfs/faculty/Dr. Y. B. Manjulatha.pdf',
    },
        {
      id: 'faculty-4',
      name: 'Dr. M. Srinivasu',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Professor & HoD',
      profile: '/public/uploads/pdfs/faculty/Dr. M. Srinivasu.pdf',
    },
    {
      id: 'faculty-5',
      name: 'Dr. N. Shiva Kumar',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Assoc. Professor & HoD',
      profile: '/public/uploads/pdfs/faculty/Dr. N. Shiva Kumar.pdf',
    },
    {
      id: 'faculty-6',
      name: 'Dr. T. Yamini Kumari',
      qualification: 'M.Pharmacy, Ph.D.',
      designation: 'Assoc. Professor & HoD',
      profile: '/public/uploads/pdfs/faculty/Dr. T. Yamini Kumari.pdf',
    },
    
    {
      id: 'faculty-7',
      name: 'Mr. P. Rambabu',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Mr P. Rambabu.pdf',
    },
    {
      id: 'faculty-8',
      name: 'Mr. Dhabal Kumar Satapathy',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Mr. Dhabal Kumar Satapathy.pdf',
    },
    {
      id: 'faculty-9',
      name: 'Mr. S. Sumanth Kamatham',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Mr. S. Sumanth Kamatham.pdf',
    },
    {
      id: 'faculty-10',
      name: 'Mrs. K. Kalyani',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Mrs. K. Kalyani.pdf',
    },
    {
      id: 'faculty-11',
      name: 'Mrs. M. Sharmila',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Mrs. M. Sharmila.pdf',
    },
    {
      id: 'faculty-12',
      name: 'Mrs. B. Vijaya Ambica Durga',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Mrs. B. Vijaya Ambica Durga.pdf',
    },
    {
      id: 'faculty-13',
      name: 'Mr. J. N. B. Indu Sekhar',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Mr. J. N. B. Indu Sekhar.pdf',
    },
    
    {
      id: 'faculty-14',
      name: 'Ms. P. Esther',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Ms. P. Esther.pdf',
    },
    {
      id: 'faculty-15',
      name: 'Mr. M. Ajay Rathnam',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Mr. M. Ajay Rathnam.pdf',
    },
    {
      id: 'faculty-17',
      name: 'Mrs. P. Thirupathamma',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Mrs. P. Thirupathamma.pdf',
    },
    {
      id: 'faculty-18',
      name: 'Ms. K. Rajeswari',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Ms. K. Rajeswari.pdf',
    },
    {
      id: 'faculty-19',
      name: 'Mrs. D. Bindu',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Mrs. D. Bindu.pdf',
    },
        {
      id: 'faculty-20',
      name: 'Mr. P. Srinu',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Mr. P. Srinu.pdf',
    },
    {
      id: 'faculty-22',
      name: 'Mrs. A. Durga Pallavi',
      qualification: 'M.Pharmacy',
      designation: 'Assoc. Professor',
      profile: '/public/uploads/pdfs/faculty/Mrs. A. Durga Pallavi.pdf',
    },
    {
      id: 'faculty-23',
      name: 'Mrs. B. Pallavi',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Mrs. B. Pallavi.pdf',
    },
    {
      id: 'faculty-24',
      name: 'Mrs. V. Sri Sowmya',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Ms. V. Sri Sowmya.pdf',
    },
    {
      id: 'faculty-25',
      name: 'Mr. K. Siva Teja',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Mr. K. Siva Teja.pdf',
    },
        {
      id: 'faculty-26',
      name: 'Ms. P. Sravanthi',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Ms. P. Sravanthi.pdf',
    },
    {
      id: 'faculty-27',
      name: 'Ms. G. Lalitha Sarojini',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Ms. G. Lalitha Sarojini.pdf',
    },
    {
      id: 'faculty-29',
      name: 'Ms. D. Rachel Shalini',
      qualification: 'M.Pharmacy',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Ms. D. Rachel Shalini.pdf',
    },
    
  ],
  nonTeaching: [
    {
      id: 'non-teaching-1',
      name: 'Mrs. R. Satyavathi',
      qualification: '',
      designation: 'Office Superintendent',
      profile: '',
    },
    {
      id: 'non-teaching-2',
      name: 'Mr. E. Satyanarayana',
      qualification: '',
      designation: 'Office Clerk',
      profile: '',
    },
    {
      id: 'non-teaching-3',
      name: 'Mr. S.N.S. Venkata Ratnam',
      qualification: '',
      designation: 'Technician',
      profile: '',
    },
    {
      id: 'non-teaching-4',
      name: 'Mr. M. Srinivasa Rao',
      qualification: '',
      designation: 'Technician',
      profile: '',
    },
    {
      id: 'non-teaching-5',
      name: 'Mr. Y. Kameswara Rao',
      qualification: '',
      designation: 'Technician',
      profile: '',
    },
    {
      id: 'non-teaching-6',
      name: 'Mrs. Y. Vijaya Lakshmi',
      qualification: '',
      designation: 'Assistant Librarian',
      profile: '',
    },
    {
      id: 'non-teaching-8',
      name: 'Mr. B. Satya Vara Prasad',
      qualification: '',
      designation: 'Lab Technician',
      profile: '',
    },
    {
      id: 'non-teaching-9',
      name: 'Mr. K. Sai Kumar',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-10',
      name: 'Ms. K. Supriya',
      qualification: '',
      designation: 'Library Attender',
      profile: '',
    },
    {
      id: 'non-teaching-11',
      name: 'Mr. K. Satyanarayana',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-12',
      name: 'Ms. U. Mani',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-13',
      name: 'Mr. B.J.R. Prasad',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-14',
      name: 'Mr. M.S.S.N.V.V. Gopal',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-15',
      name: 'Mrs. V. Jyothi',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-16',
      name: 'Ms. Y. Hema Latha',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-17',
      name: 'Mr. V. V. Eswara Rao',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
    {
      id: 'non-teaching-18',
      name: 'Mr. G. Kiran',
      qualification: '',
      designation: 'Attender',
      profile: '',
    },
  ],
  visiting: [
    {
      id: 'visiting-1',
      name: 'Mrs. Ch. Manjeera',
      qualification: 'M.A',
      department: 'BSH',
      subjects: 'English',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Mrs. Ch. Manjeera.pdf',
    },
    {
      id: 'visiting-2',
      name: 'Ms. P.V. Padmavathi',
      qualification: 'M.A, B.Ed',
      department: 'BSH',
      subjects: 'English',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Mrs.P.V.Padmavathi.pdf',
    },
    {
      id: 'visiting-3',
      name: 'Mr. Ch. Muthyala Rao',
      qualification: 'M.A., B.Ed',
      department: 'BSH',
      subjects: 'English',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Mr. Ch. Mutyala Rao.pdf',
    },
    {
      id: 'visiting-4',
      name: 'Ms. S. Sirisha',
      qualification: 'M.Sc.',
      department: 'BSH',
      subjects: '',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/Ms. S. Sirisha.pdf',
    },
    {
      id: 'visiting-5',
      name: 'Mr. A. Niranjana Rao',
      qualification: 'M.Tech',
      department: 'CSE',
      subjects: '',
      designation: 'Asst. Professor',
      profile: '/public/uploads/pdfs/faculty/CST_Mr. A. Niranjana Rao.pdf',
    },
  ],
};
